# do not create debug-packages
%define debug_package %{nil}

# deactivcate python bytecompiling
%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')

Name:		{{ pypi_package_name }}-{{ conad_dist_flavour }}
Version:	{{ pypi_package_version }}
Release:	0
Summary:	{{ pypi_package_name }} via {{ conad_dist_flavour }} generated by snakepit (EXPERIMENTAL)
Group:		Development/Tools
License:	UNKNOWN
Source0: %{name}-%{version}.tar.gz
BuildRoot:	%{_tmppath}/%{name}-%{version}-root
BuildRequires: /bin/bash wget make-opt-writable
AutoReqProv: no

%description
{{ pypi_package_name }} via {{ conad_dist_flavour }} generated by snakepit (EXPERIMENTAL)

%prep
%setup

%build
echo MY_USER=$USER
# clean, just in case
rm -rf /opt/{{ pypi_package_name }}
# install {{ conad_dist_flavour }} into /opt
wget -nv http://repo.continuum.io/{{ conad_dist_flavour }}/{{ conad_dist_flavour_urlprefix }}-{{ conda_dist_version }}-Linux-x86_64.sh
bash {{ conad_dist_flavour_urlprefix }}-{{ conda_dist_version }}-Linux-x86_64.sh -b -p /opt/{{ pypi_package_name }}
# bootstrap pip
/opt/{{ pypi_package_name }}/bin/conda install --yes pip
# use pip to install {{ pypi_package_name }}
/opt/{{ pypi_package_name }}/bin/pip install {{ extra_pip_args }} {{ pypi_package_name }}=={{ pypi_package_version }}

%install
# create /opt/{{ pypi_package_name }} in buildroot
mkdir -p %{buildroot}/opt/{{ pypi_package_name }}
# copy the built {{ conad_dist_flavour }} env into the buildroot
cp -r /opt/moto %{buildroot}/opt
ls %{buildroot}/opt/{{ pypi_package_name }}
# create a /usr/bin
install -m 755 -d %{buildroot}/usr/bin
# do all the symlinks
{% for item in symlinks %}
ln -s /opt/{{ pypi_package_name }}/bin/{{ item }} %{buildroot}/usr/bin
{% endfor %}

%clean
# remove the result of the build step
rm -rf /opt/{{ pypi_package_name }}

%files
%defattr(-,root,root,-)
/opt/{{ pypi_package_name }}
{% for item in symlinks %}
/usr/bin/{{ item }}
{% endfor %}

%post
