#!/usr/bin/env python
# vim: set filetype=python:

"""snakepit

Usage:
  snakepit [--debug] [(-f | --force)]<file>
  snakepit (-h | --help)
  snakepit --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --debug       Enable debug output.
  -f, --force   Force overwrite of output.

"""

from docopt import docopt
from snakepit import main

if __name__ == '__main__':
    arguments = docopt(__doc__, version="alpha")
    main(arguments)
