#!/usr/bin/env python
# vim: set filetype=python:

"""snakepit

Usage:
  snakepit [--debug] [--build=<build>] [(-f | --force)] [--output=<filename>] [--distribution=<distribution>] <file>
  snakepit (-h | --help)
  snakepit --version

Options:
  -h --help                      Show this screen.
  --version                      Show version.
  --debug                        Enable debug output.
  --build=<build>                The build number [default: 0]
  -f, --force                    Force overwrite of output.
  --output=<filename>            Filename for SPEC-File.
  --distribution=<distribution>  Python distribution to use [default: miniconda]

"""

from docopt import docopt
from snakepit import main

if __name__ == '__main__':
    arguments = docopt(__doc__, version="alpha")
    main(arguments)
