#!/usr/bin/env python
# vim: set filetype=python:

"""snakepit

Usage:
  snakepit <file>
  snakepit (-h | --help)
  snakepit --version

Options:
  -h --help     Show this screen.
  --version     Show version.

"""

from docopt import docopt
from snakepit import main

if __name__ == '__main__':
    arguments = docopt(__doc__)
    main(arguments)
